---
# Calendar service
# Exposes the Calendar application within the cluster
apiVersion: v1
kind: Service
metadata:
  name: calendar
  namespace: ddot-demo
  labels:
    app.kubernetes.io/name: calendar
    app.kubernetes.io/instance: calendar
    app.kubernetes.io/version: "1.0.0"
    tags.datadoghq.com/env: production
    tags.datadoghq.com/service: calendar
    tags.datadoghq.com/version: "1.0.0"
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: calendar
    app.kubernetes.io/instance: calendar

